import Carbon
import Cocoa
import KeylapseCore

/// Where a chooser or notice goes: just under this rectangle, or just above it.
struct TextSpot {
    let rect: NSRect
    let above: Bool
}

/// The general pasteboard, saved and put back around a correction.
struct Clipboard {
    typealias Snapshot = [[NSPasteboard.PasteboardType: Data]]

    /// Tells clipboard managers that what Keylapse writes is passing through and is not the
    /// user's own copy, so it stays out of their history (the nspasteboard.org convention).
    private static let transientTypes = ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        .map { NSPasteboard.PasteboardType($0) }

    private let pasteboard = NSPasteboard.general

    var changeCount: Int { pasteboard.changeCount }
    var text: String? { pasteboard.string(forType: .string) }

    func snapshot() -> Snapshot {
        (pasteboard.pasteboardItems ?? []).map { item in
            var types: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types { if let data = item.data(forType: type) { types[type] = data } }
            return types
        }
    }

    func restore(_ snapshot: Snapshot) {
        let items = snapshot.map { types -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: type) }
            return item
        }
        pasteboard.clearContents()
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    /// Empties the pasteboard and returns its change count, to tell when an app has copied into it.
    func clear() -> Int {
        pasteboard.clearContents()
        return pasteboard.changeCount
    }

    /// Puts text on the pasteboard, marked as transient, and returns the change count.
    func write(_ text: String) -> Int {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        for type in Self.transientTypes { pasteboard.setData(Data(), forType: type) }
        return pasteboard.changeCount
    }
}

/// Replaces the selected text of the app in front with its corrected form.
///
/// The text is read first: through Accessibility where the app hands it over (`selection`),
/// by a quiet copy where it does not (`probeSelection`). The replacement is pasted, so the
/// editor's own Undo takes it back, and the clipboard is put back afterwards.
final class SelectionCorrector {
    enum Selection: Equatable {
        case none
        case text(String)
        /// The app does not say; many web views and Electron apps expose neither the selected
        /// text nor its range.
        case unknown
    }

    private(set) var busy = false
    /// Called once the replacement has been made, before `completion`.
    var didReplace: (() -> Void)?
    var completion: ((Result<Void, Error>) -> Void)?

    private let clipboard = Clipboard()
    private static let ownPID = ProcessInfo.processInfo.processIdentifier
    /// How long an app gets to act on a paste before the clipboard is put back.
    private static let pasteDelay: TimeInterval = 0.7
    private static let selectFirst = AppError.message("Select the text you want to fix first.")

    // MARK: Reading the selection

    func selection(in pid: pid_t) -> Selection {
        if pid == Self.ownPID {
            guard let editor = ownEditor else { return .none }
            return .text((editor.string as NSString).substring(with: editor.selectedRange()))
        }
        guard let element = focusedElement(pid) else { return .unknown }
        if let text = stringAttribute(element, kAXSelectedTextAttribute) { return text.isEmpty ? .none : .text(text) }
        var value: CFTypeRef?
        if AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &value) == .success,
           let value, CFGetTypeID(value) == AXValueGetTypeID() {
            var range = CFRange()
            if AXValueGetValue(value as! AXValue, .cfRange, &range), range.length == 0 { return .none }
        }
        return .unknown
    }

    /// For apps that do not say: copies quietly and hands over the text that came out, then puts
    /// the clipboard back. An app answers a copy within a few hundredths of a second, so a
    /// selection is confirmed almost at once and only "nothing selected" waits the full 0.4 s.
    func probeSelection(completion: @escaping (String?) -> Void) {
        guard !busy, AXIsProcessTrusted() else { completion(nil); return }
        busy = true
        waitForModifiers(deadline: ProcessInfo.processInfo.systemUptime + 0.5) { [weak self] released in
            guard let self else { return }
            guard released else { self.busy = false; completion(nil); return }
            let snapshot = self.clipboard.snapshot()
            let emptied = self.clipboard.clear()
            self.sendCommand("c")
            self.pollProbe(emptied: emptied, snapshot: snapshot, deadline: Date().addingTimeInterval(0.4), completion: completion)
        }
    }

    private func pollProbe(emptied: Int, snapshot: Clipboard.Snapshot, deadline: Date, completion: @escaping (String?) -> Void) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.02) { [weak self] in
            guard let self else { return }
            // Web editors can declare clipboard types before supplying the text, so a changed
            // count alone does not mean the copy has finished.
            let text = self.clipboard.changeCount != emptied ? self.clipboard.text : nil
            let copied = !(text ?? "").isEmpty
            if !copied && Date() < deadline {
                self.pollProbe(emptied: emptied, snapshot: snapshot, deadline: deadline, completion: completion)
                return
            }
            self.clipboard.restore(snapshot)
            self.busy = false
            completion(copied ? text : nil)
        }
    }

    /// Remembers the selection so that it can be checked again later, after a chooser has held
    /// the keyboard or the shortcut keys have been released.
    func selectionCheck(for pid: pid_t) -> () -> Bool {
        guard let element = focusedElement(pid) else { return { true } }
        let text = stringAttribute(element, kAXSelectedTextAttribute)
        var range: CFTypeRef?
        _ = AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &range)
        return { [weak self] in
            guard let self, let current = self.focusedElement(pid), CFEqual(current, element) else { return false }
            if let text, self.stringAttribute(current, kAXSelectedTextAttribute) != text { return false }
            if let range {
                var currentRange: CFTypeRef?
                guard AXUIElementCopyAttributeValue(current, kAXSelectedTextRangeAttribute as CFString, &currentRange) == .success,
                      let currentRange, CFEqual(range, currentRange) else { return false }
            }
            return true
        }
    }

    /// Where the selected text is on screen, in Cocoa coordinates, so a chooser can appear
    /// next to it: under the selected text, or, in apps that do not say where the selection is
    /// (many web views and custom editors) but do say where the field is, above the field when
    /// it is a short one such as a message box, which usually sits at the bottom of its window.
    /// Nil otherwise.
    func selectionSpot(for pid: pid_t) -> TextSpot? {
        guard let element = focusedElement(pid) else { return nil }
        if let rect = selectionBounds(of: element) { return TextSpot(rect: rect, above: false) }
        guard let field = frame(of: element), field.height <= Self.shortFieldHeight else { return nil }
        return TextSpot(rect: field, above: true)
    }

    private static let shortFieldHeight: CGFloat = 120

    private func selectionBounds(of element: AXUIElement) -> NSRect? {
        var range: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXSelectedTextRangeAttribute as CFString, &range) == .success, let range else { return nil }
        var value: CFTypeRef?
        guard AXUIElementCopyParameterizedAttributeValue(element, kAXBoundsForRangeParameterizedAttribute as CFString, range, &value) == .success,
              let value, CFGetTypeID(value) == AXValueGetTypeID() else { return nil }
        var rect = CGRect.zero
        guard AXValueGetValue(value as! AXValue, .cgRect, &rect), rect.height > 0, rect != .zero else { return nil }
        return cocoaRect(rect)
    }

    private func frame(of element: AXUIElement) -> NSRect? {
        var position: CFTypeRef?
        var size: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, kAXPositionAttribute as CFString, &position) == .success,
              AXUIElementCopyAttributeValue(element, kAXSizeAttribute as CFString, &size) == .success,
              let position, let size, CFGetTypeID(position) == AXValueGetTypeID(), CFGetTypeID(size) == AXValueGetTypeID() else { return nil }
        var origin = CGPoint.zero
        var extent = CGSize.zero
        guard AXValueGetValue(position as! AXValue, .cgPoint, &origin), AXValueGetValue(size as! AXValue, .cgSize, &extent),
              extent.height > 0, extent.width > 0 else { return nil }
        return cocoaRect(CGRect(origin: origin, size: extent))
    }

    /// Accessibility measures from the top left of the main display; Cocoa from its bottom left.
    private func cocoaRect(_ rect: CGRect) -> NSRect? {
        guard let main = NSScreen.screens.first else { return nil }
        return NSRect(x: rect.minX, y: main.frame.height - rect.maxY, width: rect.width, height: rect.height)
    }

    // MARK: Replacing it

    /// Replaces the selection, known to hold `text`, with `converted`: the same keys on the
    /// layout the text was meant for.
    func replace(_ text: String, with converted: String) {
        guard !busy else { return }
        guard AXIsProcessTrusted() else {
            completion?(.failure(AppError.message("Enable Keylapse in Privacy & Security → Accessibility.")))
            return
        }
        guard let app = NSWorkspace.shared.frontmostApplication else { return }
        // Keylapse's own window counts too: the welcome page corrects a word in its text field.
        // There the text is replaced directly. Copy and paste sent to itself do not arrive
        // reliably (a menu bar app has no key window while its chooser is closing), and the
        // user's clipboard has no reason to be touched for a field Keylapse owns.
        if app.processIdentifier == Self.ownPID {
            replaceInOwnField(text, with: converted)
            return
        }
        let selectionUnchanged = selectionCheck(for: app.processIdentifier)
        busy = true
        // The shortcut keys must be up, or the paste would arrive as a different shortcut.
        waitForModifiers(deadline: ProcessInfo.processInfo.systemUptime + 0.5) { [weak self] released in
            guard let self else { return }
            guard released else { return self.finish(.failure(AppError.message("Release the shortcut keys and try again."))) }
            guard NSWorkspace.shared.frontmostApplication?.processIdentifier == app.processIdentifier, selectionUnchanged() else {
                return self.finish(.failure(AppError.message("The app or selection changed; correction was cancelled.")))
            }
            let snapshot = self.clipboard.snapshot()
            let written = self.clipboard.write(converted)
            self.sendCommand("v")
            DispatchQueue.main.asyncAfter(deadline: .now() + Self.pasteDelay) { [weak self] in
                guard let self else { return }
                // Don't overwrite a newer clipboard value created by the user or another app.
                if self.clipboard.changeCount == written { self.clipboard.restore(snapshot) }
                self.finish(.success(()))
            }
        }
    }

    private func finish(_ result: Result<Void, Error>) {
        busy = false
        if case .success = result { didReplace?() }
        completion?(result)
    }

    private var ownEditor: NSTextView? {
        NSApp.windows.compactMap { $0.firstResponder as? NSTextView }.first { $0.selectedRange().length > 0 }
    }

    private func replaceInOwnField(_ text: String, with converted: String) {
        guard let editor = ownEditor else {
            completion?(.failure(Self.selectFirst))
            return
        }
        let range = editor.selectedRange()
        do {
            guard (editor.string as NSString).substring(with: range) == text else {
                throw AppError.message("The app or selection changed; correction was cancelled.")
            }
            // Through the text system, so the field's owner hears of it and ⌘Z undoes it.
            guard editor.shouldChangeText(in: range, replacementString: converted) else {
                throw AppError.message("This field cannot be edited.")
            }
            editor.replaceCharacters(in: range, with: converted)
            editor.didChangeText()
            editor.setSelectedRange(NSRange(location: range.location, length: (converted as NSString).length))
            finish(.success(()))
        } catch { finish(.failure(error)) }
    }

    // MARK: Keys

    private static let modifierKeys: [CGKeyCode] = [54, 55, 56, 60, 58, 61, 59, 62, 63]

    private var modifierKeyIsDown: Bool {
        Self.modifierKeys.contains { CGEventSource.keyState(.hidSystemState, key: $0) }
    }

    private func waitForModifiers(deadline: TimeInterval, then: @escaping (Bool) -> Void) {
        guard modifierKeyIsDown else { then(true); return }
        guard ProcessInfo.processInfo.systemUptime < deadline else { then(false); return }
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) { [weak self] in self?.waitForModifiers(deadline: deadline, then: then) }
    }

    /// Sends ⌘C or ⌘V to the app in front. Apps match these by letter, and a layout such as
    /// Dvorak has its letters on other keys, so the key is looked up in the active layout:
    /// with Command held first (non-Latin layouts type Latin letters then), then without.
    /// A layout with neither falls back to the QWERTY position, which macOS maps for it.
    private func sendCommand(_ letter: String) {
        let layout = TISCopyCurrentKeyboardLayoutInputSource().takeRetainedValue()
        let found = [cmdKey, 0].lazy.compactMap { modifiers in
            (UInt16(0)...50).first { InputSources.translate(layout, key: $0, modifiers: modifiers)?.lowercased() == letter }
        }.first
        let code = found ?? (letter == "c" ? 8 : 9)
        let source = CGEventSource(stateID: .privateState)
        for down in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: code, keyDown: down)
            // Leaving Command on key-up makes macOS retain a pressed Command
            // key after our own copy, which then cancels the replacement.
            event?.flags = down ? .maskCommand : []
            event?.setIntegerValueField(.eventSourceUserData, value: KeyboardMonitor.ownEventTag)
            event?.post(tap: .cghidEventTap)
        }
    }

    // MARK: Accessibility

    private func focusedElement(_ pid: pid_t) -> AXUIElement? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(AXUIElementCreateApplication(pid), kAXFocusedUIElementAttribute as CFString, &value) == .success,
              let value, CFGetTypeID(value) == AXUIElementGetTypeID() else { return nil }
        return (value as! AXUIElement)
    }

    private func stringAttribute(_ element: AXUIElement, _ name: String) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? String
    }
}
